### ISSUE TITLE
Notes?

### ISSUE THREAD

**Issue by sansari** [jammastergirish/Readwise2Roam#1]
When I did the export+import, it seems like it did not import any of my Notes on the highlights. Is this by design?

Basically without the notes, the highlights are a lot less useful for me, so would be awesome to have those included!

**Comment by jammastergirish** [comment]
Thanks! Good point. I’ve never actually used the notes feature, only taken highlights. That should be easy to implement as it’s just another field in the Readwise CSV. I’ll take a look.

**Comment by jammastergirish** [comment]
I've created a new branch, `adds_notes`. I've tested it with only highlights. Would you mind testing with highlights and notes, please? If it works well, will merge with `master` and your idea will have been implemented!

**Comment by sansari** [comment]
Thanks @jammastergirish! I tested it out locally, and it imports the highlights now. I think that's a big help! Closing this issue.

P.S. I should note that on my end, i actually have automatic export to EverNote setup already. You can then see all your Readwise notes there, and I basically just copy them from there into Roam. They also include actual location links etc... Anyway, I only point this out because I think for anyone who has EverNote, using this tool will be a bit more work / probably not worth it. However, for anyone who DOESN'T have evernote (i assume that's your target audience), this will be great. Hope it's helpful just to know. Thanks again for this tool!
